"use client";
import React, { useEffect, useRef, useState } from "react";
import Typed from "typed.js";

export default function Header({ activeSection, setActiveSection }) {
  const typedRef = useRef(null);
  const [mobileOpen, setMobileOpen] = useState(false);

  useEffect(() => {
    const typed = new Typed(typedRef.current, {
      strings: ["frontend", "creative", "dedicated", "DevOps enthusiast", "problem-solver", "UI/UX focused"],
      loop: true,
      typeSpeed: 80,
      backSpeed: 40,
      backDelay: 2000,
    });

    return () => {
      typed.destroy();
    };
  }, []);

  const handleClick = (e, section) => {
    e.preventDefault();
    setActiveSection(section);
    setMobileOpen(false);
  };

  return (
    <header id="header" style={{ zIndex: activeSection === "header" ? 1 : 0 }}>
      <div className="container">
        <h1>
          <a href="#header" onClick={(e) => handleClick(e, "header")}>Erioluwa Morakinyo</a>
        </h1>
        <h2>
          your very own <span className="typed" ref={typedRef}></span> developer.
        </h2>

        <nav id="navbar" className={`navbar ${mobileOpen ? "mobile-open" : ""}`}>
          <ul>
            <li>
              <a className={`nav-link ${activeSection === "header" ? "active" : ""}`} href="#header" onClick={(e) => handleClick(e, "header")}>
                <span>Home</span>
              </a>
            </li>
            <li>
              <a className={`nav-link ${activeSection === "about" ? "active" : ""}`} href="#about" onClick={(e) => handleClick(e, "about")}>
                <span>About</span>
              </a>
            </li>
            <li>
              <a className={`nav-link ${activeSection === "resume" ? "active" : ""}`} href="#resume" onClick={(e) => handleClick(e, "resume")}>
                <span>Resume</span>
              </a>
            </li>
            <li>
              <a className={`nav-link ${activeSection === "portfolio" ? "active" : ""}`} href="#portfolio" onClick={(e) => handleClick(e, "portfolio")}>
                <span>Projects</span>
              </a>
            </li>
            <li>
              <a className={`nav-link ${activeSection === "contact" ? "active" : ""}`} href="#contact" onClick={(e) => handleClick(e, "contact")}>
                <span>Contact</span>
              </a>
            </li>
          </ul>
          <i
            className={`bi mobile-nav-toggle ${mobileOpen ? "bi-x" : "bi-list"}`}
            onClick={() => setMobileOpen(!mobileOpen)}
          ></i>
        </nav>

        <div className="social-links">
          <a href="https://github.com/EriMorak7" target="_blank" rel="noopener noreferrer" className="github">
            <i className="bx bxl-github"></i>
          </a>
          <a href="https://www.linkedin.com/in/erioluwa-morakinyo-149354370/" target="_blank" rel="noopener noreferrer" className="linkedin">
            <i className="bx bxl-linkedin"></i>
          </a>
          <a href="https://www.instagram.com/erimorak7/" target="_blank" rel="noopener noreferrer" className="instagram">
            <i className="bx bxl-instagram"></i>
          </a>
        </div>
      </div>

      <div className="footer-text">This footer was not generated by AI... or was it? 🤖</div>
    </header>
  );
}
